version: '2'

services:

  matchapimongodb:
    image: mongo
    volumes:
      - "~/matchapidb:/data/db"
    networks:
      - matchapimongo

  matchapispringbootmongo:
    build: .
    #image: dgomezdeveloper/match-api-springboot-service:firsttry
    depends_on:
      - matchapimongodb
    ports:
      - "5000:8080"
    networks:
      - matchapimongo

networks:
  matchapimongo:
