apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: matchapispringbootmongo
  name: matchapispringbootmongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: matchapispringbootmongo
    spec:
      containers:
      - image: dgomezdeveloper/match-api-springboot-service:firsttry
        name: matchapispringbootmongo
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
