apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: matchapimongodb
  name: matchapimongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: matchapimongodb
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: matchapimongodb
        appdb: matchapimongodb
    spec:
      containers:
      - image: mongo
        name: matchapimongodb
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: matchapimongodb-claim0
      restartPolicy: Always
      volumes:
      - name: matchapimongodb-claim0
        persistentVolumeClaim:
          claimName: matchapimongodb-claim0
status: {}
